# EIG9100 hardware platform
# CPU: TI AM3352 800MHz, 512MB DDR3
# SPI Flash
# EMMC
export PLATFORM_RELFLAGS+=-DCONFIG_HARDWARE_EIG9100
export PLATFORM_RELFLAGS+=-DCONFIG_SYS_CUSTOMIZE_MPUCLK=800
export PLATFORM_RELFLAGS+=-DCONFIG_UBOOT_HAS_DDR3
export PLATFORM_RELFLAGS+=-DDDR3_NT5CC256M16DP_DI
export PLATFORM_RELFLAGS+=-DCONFIG_UBOOT_SYS_BOOT_LEN=32
export PLATFORM_RELFLAGS+=-DCONFIG_SPI_FLASH_SIZE_32MIB
export PLATFORM_RELFLAGS+=-DCONFIG_UBOOT_HAS_LTE_PLS8X
