interface_arping: interface_arping.o
	$(CC) $(EXTRA_CFLAGS) $(LDFLAGS) interface_arping.o -o interface_arping

interface_arping.o: interface_arping.c
	$(CC) $(EXTRA_CFLAGS) $(LDFLAGS) -c interface_arping.c

clean:
	rm *.o interface_arping
