#!/bin/sh

uci -q batch <<-EOF >/dev/null
	add ucitrack locator
	set ucitrack.@locator[0].init=locator
	add_list ucitrack.@network[0].affects=locator
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
