#!/bin/sh

uci -q batch <<-EOF >/dev/null
del ucitrack.@openlldpd[-1]
add ucitrack openlldpd
set ucitrack.@openlldpd[0].init=openlldpd
del_list ucitrack.@network[0].affects=openlldpd
add_list ucitrack.@network[0].affects=openlldpd
commit ucitrack
commit
EOF
