#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=11

boot() {
	if [ "`uci get functionlist.vendorlist.FIXED_REGULAR_DOMAIN`" = "FCC" ]; then
		setconfig -a 1;setconfig -a 2 -s 4 -d 0
	elif [ "`uci get functionlist.vendorlist.FIXED_REGULAR_DOMAIN`" = "ETSI" ]; then
		setconfig -a 1;setconfig -a 2 -s 4 -d 1
	elif [ "`uci get functionlist.vendorlist.FIXED_REGULAR_DOMAIN`" = "INT" ]; then
		setconfig -a 1;setconfig -a 2 -s 4 -d 2
	fi
}
