#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1

start_service() {
	config_load guestsyncd
	config_get_bool enabled guestsyncd enabled 0

	if [ "1" == "$enabled" ]; then
		config_get interface guestsyncd interface
		config_get networkId guestsyncd networkId
		config_get group guestsyncd group $networkId
		procd_open_instance
		procd_set_param command /usr/sbin/guest_syncd -i $interface ${group:+-g "$group"} ${DEBUG+-dddddd}
		procd_set_param respawn
		if [ ${DEBUG:-0} -eq 1 ]
		then
			procd_set_param stdout 1
			procd_set_param stderr 1
		fi
		procd_close_instance
	fi
}

reload_service()
{
	stop
	start
}

