#!/bin/sh /etc/rc.common
#
# Copyright (c) 2017 Qualcomm Technologies, Inc.
#
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.
#
# Copyright (c) 2016, The Linux Foundation. All rights reserved.
#

START=15

boot() {

#	echo "For Senao fastroaming of spf5.2 qca_hostap, we run multiple hostapd instances for all radio's. "
	if  [ -e "/var/run/hostapd-global.pid" ]
	then
		kill $(cat /var/run/hostapd-global.pid) &> /dev/null
		rm /var/run/hostapd-global.pid &> /dev/null
	fi
	hostapd -g /var/run/hostapd/global -B -P /var/run/hostapd-global.pid
}
