#!/bin/sh /etc/rc.common
# (C) 2008 openwrt.org

START=99

SERVICE_USE_PID=1


boot()
{
	exit 0 #for throughput issue, NOT to do fastscan when stand alone
	/usr/shc/setfastscan boot
}

start()
{
	/usr/shc/setfastscan start
}
stop()
{
	/usr/shc/setfastscan stop
}
