#!/bin/sh /etc/rc.common

#Shpin add

START=99
STOP=10

boot() {
	/usr/shc/snmpdtrap boot
}


start() {
	/usr/shc/snmpdtrap start
}

restart() {
	/usr/shc/snmpdtrap restart
}

stop() {
	/usr/shc/snmpdtrap stop
}

