/*
* mi_dma_datatype.h- Sigmastar
*
* Copyright (C) 2018 Sigmastar Technology Corp.
*
* Author: XXXX <XXXX@sigmastar.com.cn>
*
* This software is licensed under the terms of the GNU General Public
* License version 2, as published by the Free Software Foundation, and
* may be copied, distributed, and modified under those terms.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
*/
#ifndef _MI_DMA_DATATYPE_H_
#define _MI_DMA_H_
#include "mi_common.h"

#define MI_DMA_SUCCESS MI_SUCCESS// do not use MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, MI_SUCCESS)   !!!!

/* DMA Module ErrorCode */
#define MI_ERR_DMA_INVALID_DEVID MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, E_MI_ERR_INVALID_DEVID)
#define MI_ERR_DMA_INVALID_CHNID MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, E_MI_ERR_INVALID_CHNID)
#define MI_ERR_DMA_ILLEGAL_PARAM MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, E_MI_ERR_ILLEGAL_PARAM)
#define MI_ERR_DMA_EXIST MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, E_MI_ERR_EXIST)
#define MI_ERR_DMA_UNEXIST MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, E_MI_ERR_UNEXIST)
#define MI_ERR_DMA_NULL_PTR MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, E_MI_ERR_NULL_PTR)
#define MI_ERR_DMA_NOT_CONFIG MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, E_MI_ERR_NOT_CONFIG)
#define MI_ERR_DMA_NOT_SUPPORT MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, E_MI_ERR_NOT_SUPPORT)
#define MI_ERR_DMA_NOT_PERM MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, E_MI_ERR_NOT_PERM)
#define MI_ERR_DMA_NOMEM MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, E_MI_ERR_NOMEM)
#define MI_ERR_DMA_NOBUF MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, E_MI_ERR_NOBUF)
#define MI_ERR_DMA_BUF_EMPTY MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, E_MI_ERR_BUF_EMPTY)
#define MI_ERR_DMA_BUF_FULL MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, E_MI_ERR_BUF_FULL)
#define MI_ERR_DMA_DMA_NOTREADY MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, E_MI_ERR_DMA_NOTREADY)
#define MI_ERR_DMA_BADADDR MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, E_MI_ERR_BADADDR)
#define MI_ERR_DMA_BUSY MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, E_MI_ERR_BUSY)
#define MI_ERR_DMA_CHN_NOT_STARTED MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, E_MI_ERR_CHN_NOT_STARTED)
#define MI_ERR_DMA_CHN_NOT_STOPED MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, E_MI_ERR_CHN_NOT_STOPED)
#define MI_ERR_DMA_NOT_INIT MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, E_MI_ERR_NOT_INIT)
#define MI_ERR_DMA_NOT_ENABLE MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, E_MI_ERR_NOT_ENABLE)
#define MI_ERR_DMA_FAILED MI_DEF_ERR(E_MI_MODULE_ID_DMA, E_MI_ERR_LEVEL_ERROR, E_MI_ERR_FAILED)

#endif //_MI_DMA_DATATYPE_H_