#
# Automatically generated make config: don't edit
# version: 
#

#
# -- SENAO NETWORK VENDOR CONFIG --
#

#
# Partition Info
#
CONFIG_BOOTLOADER_PARTITION_NAME="0:APPSBL"
CONFIG_BOOTLOADER_CONFIG_PARTITION_NAME="u-boot-env"
CONFIG_KERNEL_PARTITION_NAME="kernel"
CONFIG_APP_STORAGE_PARTITION_NAME="rootfs"
CONFIG_COMBINED_APP_PARTITION_NAME="firmware"

#
# Vendor Config
#
CONFIG_ENGENIUS=y
# CONFIG_SITECOM is not set
# CONFIG_SigmaStar is not set
# CONFIG_GENERIC is not set
# CONFIG_PAKEDGE is not set
# CONFIG_MERAKI is not set
# CONFIG_IODATA is not set
# CONFIG_TORCH is not set
# CONFIG_FORTINET is not set
# CONFIG_ATKK is not set
# CONFIG_WINMATE is not set
# CONFIG_LANYO is not set

#
# Product Info
#
CONFIG_MODEL_NAME="EAP1300"
CONFIG_SUPPORT_MODEL="EAP1300"
CONFIG_VENDOR_NAME="EnGenius"
CONFIG_RADIO_MODE=7
CONFIG_ROUTER_MODE=0
CONFIG_AP_WSC_MODEL_NAME="Wireless Gigabit Router"
CONFIG_AP_WSC_DEVICE_NAME="Wireless Gigabit Router"
CONFIG_AP_WSC_MANUFACTURE="SENAO"
CONFIG_UPNPD_FRIENDLY_NAME="Wi-Fi Router X8 AC2600"
CONFIG_UPNPD_MANUFACTURE="SENAO"
CONFIG_UPNPD_MANUFACTURE_URL="http://www.senao.com.tw"
CONFIG_UPNPD_MODEL_DESC="Wi-Fi Router X8 AC2600"
CONFIG_UPNPD_MODEL_NAME="Wi-Fi Router X8 AC2600"
CONFIG_UPNPD_MODEL_NUMBER="EAP1300"
CONFIG_UPNPD_MODEL_URL="http://www.senao.com.tw"
CONFIG_ANTENNA_NUM=2
CONFIG_SUPPORT_11AC=1
# CONFIG_SENAO_MKIMAGE_CHECK_ROOTFS is not set

#
# Bluetooth Setting Info
#
CONFIG_BT_API_ODM_KEY=16

#
# App agent Setting Info
#
CONFIG_APP_AGENT_AES_KEY_BASIC_DATA="$~EnGeniuS!^ApP&#sErViCe?@"
CONFIG_APP_AGENT_SUPPORT_DDNS_TYPE_3322=0
CONFIG_APP_AGENT_SUPPORT_DDNS_TYPE_DYNDNS=0
CONFIG_APP_AGENT_SUPPORT_DDNS_TYPE_ZONEEDIT=0
CONFIG_APP_AGENT_SUPPORT_DDNS_TYPE_NO_IP=0
CONFIG_APP_AGENT_SUPPORT_DDNS_TYPE_ENGENIUS=0
CONFIG_APP_AGENT_SUPPORT_ENSHARE=0

#
# Option Setting Info
#
CONFIG_WIFI_RADIO_NUM=2
CONFIG_NTP_SERVER_NUM=3
CONFIG_MAC_FILTER_NUM=256
CONFIG_NUM_LAN_MAC_FILTERS=20
CONFIG_DNS_SERVER_NUM=4
CONFIG_WDS_MAC_NUM=8
CONFIG_WIFI_SSID_NUM=8
CONFIG_MAX_WIFI_CLIENT_NUM=128

#
# Interface  Info
#
CONFIG_BRG_DEV="br-lan"
CONFIG_BRG_DEV_AVAHI="br-lan:avahi"
CONFIG_WAN_IF=""
CONFIG_LAN_IF="eth1"
# CONFIG_HAS_LAN2_IF is not set
CONFIG_LAN2_IF=""
CONFIG_WIFI_24G_IF="ath0"
CONFIG_WIFI_5G_IF="ath1"
CONFIG_WIFI_5G_2_IF="ath4"
CONFIG_WIFI_24G="wifi0"
CONFIG_WIFI_5G="wifi1"
CONFIG_WIFI_5G_2="wifi2"
CONFIG_AP_WIFI_IFACE_NUM=8
CONFIG_STA_WIFI_IFACE_NUM=0
CONFIG_WDSB_WIFI_IFACE_NUM=1
CONFIG_WDSAP_AP_WIFI_IFACE_NUM=4
CONFIG_WDSAP_WDS_WIFI_IFACE_NUM=1
CONFIG_WDSSTA_WIFI_IFACE_NUM=0
CONFIG_STA_PROFILE_NUM=0
CONFIG_AP_WIFI_24G_IFACE_NO=0
CONFIG_AP_WIFI_5G_IFACE_NO=8
CONFIG_WDSB_WIFI_24G_IFACE_NO=0
CONFIG_WDSB_WIFI_5G_IFACE_NO=0
CONFIG_WDSAP_WIFI_24G_WDS_IFACE_NO=0
CONFIG_WDSAP_WIFI_5G_WDS_IFACE_NO=0
CONFIG_WDSAP_WIFI_24G_IFACE_NO=0
CONFIG_WDSAP_WIFI_5G_IFACE_NO=0
CONFIG_WDSSTA_WIFI_24G_IFACE_NO=0
CONFIG_WDSSTA_WIFI_5G_IFACE_NO=0
CONFIG_STA_WIFI_24G_IFACE_NO=0
CONFIG_STA_WIFI_5G_IFACE_NO=0

#
# rmgmt setting
#
CONFIG_SEPARATION=","
CONFIG_LED_GPIO_2G_NAME=""
CONFIG_LED_GPIO_5G_NAME=""
# CONFIG_HAS_RMGMT_IF is not set
CONFIG_RMGMT_IF=""
CONFIG_HAS_RMGMT_THIRD_RADIO=y

#
# File Path Info
#
CONFIG_WIFI_IF_PATH=""

#
# Parameter Info
#
CONFIG_MAX_CLIENT_PERSON=12
CONFIG_MAX_CLIENT_DEVICE=32
CONFIG_MAX_FIREWALL_EBTABLES_RULE=16
CONFIG_MAX_FIREWALL_BLOCK_ITEM=10
CONFIG_MAX_FIREWALL_BLOCK_ITEM_LEN=32

#
# IP address
#
CONFIG_LOCAL_IP="192.168.1.1"
CONFIG_REMOTE_IP="192.168.1.10"

#
# LED Control
#
CONFIG_LED_POWER="power_led"
CONFIG_LED_LAN="lan1_led"
CONFIG_LED_WIFI0="wifi0_led"
CONFIG_LED_WIFI1="wifi1_led"
CONFIG_LED_WIFI2="wifi2_led"
CONFIG_LED_MESH="mesh_led"

#
# Factory config
#
CONFIG_HAS_USB_TO_SDCARD=0
CONFIG_HAS_SWITCH_PORT=4
CONFIG_HAS_TWO_PHY_ETHER_TWO_LAN_PORT=0
CONFIG_HAS_TWO_PHY_ETHER_LAN_WAN_PORT=0
# CONFIG_HAS_BLUETOOTH_MODULE is not set
CONFIG_BT_DEV_NAME=""
CONFIG_HAS_ATH_PCIE_DETECT_TEST=y
CONFIG_PCIE_IRQ_NUMBER_24G=0
CONFIG_PCIE_IRQ_NUMBER_5G=0
CONFIG_PCIE_IRQ_NUMBER_5G_2=0
CONFIG_HAS_RTC_HWCLOCK=0

#
# -- SENAO NETWORK VENDOR CONFIG --
#
